name: Miri (Undefined Behavior Checker)
on:
  push:
  pull_request:
jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Rust nightly with Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup default nightly
      
      - name: Verify Miri installation
        run: cargo +nightly miri setup
      
      - name: Run tests under Miri
        run: cargo +nightly miri test
