name: Miri

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly and Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup default nightly

      - name: Run tests under Miri
        run: cargo +nightly miri test
